extends:
  - airbnb
  - plugin:flowtype/recommended
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
globals:
  window: true
  document: true
settings:
  import/resolver:
    webpack:
      config: 'config/webpack.config.prod.js'
rules:
  global-require: 0
  # import/no-duplicates tests same but is also flow-aware
  no-duplicate-imports: 0
  no-case-declarations: 0
  no-confusing-arrow: 0
  class-methods-use-this: 2
  no-restricted-syntax: 0
  arrow-body-style: 0
  comma-dangle: [ 2, {
    arrays: always-multiline,
    objects: always-multiline,
    imports: always-multiline,
    exports: always-multiline,
    functions: ignore,
  }]
  jsx-a11y/no-static-element-interactions: 0
  react/prefer-stateless-function: 0
  react/no-unused-prop-types: 0
  react/jsx-no-bind: 0
  react/sort-comp:
    - 1
    - order:
      - type-annotations
      - static-methods
      - lifecycle
      - everything-else
      - render
  import/no-named-as-default: 0
